name: kitzo

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test:
    name: Test & Build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Pull the project code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm (package manager)
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install node (js runtime)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build test
        run: pnpm build

  release:
    name: Package release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Pull the project code
        uses: actions/checkout@v4

      - name: Install pnpm (package manager)
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install node (js runtime)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Bump version, Commit changes, publish package
        uses: changesets/action@v1
        with:
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
